name: lsp
description: Dart LSP client
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
