name: lsp
description: Dart LSP client
version: 2.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
